### ISSUE TITLE
RuntimeError: number of dims don't match in permute

### ISSUE THREAD

**Issue by zzutopia** [christy1206/STSTNet#4]
When I use Google GPU to run Python code, I encounter this problem. How can I solve it? Hope to get your reply

lr=0.000050, epochs=800, device=cuda

Subject: sub25
Predicted    : [0, 0, 0, 2, 2]
Ground Truth : [0, 0, 0, 2, 2]
Evaluation until this subject: 
UF1: 1.0 | UAR: 1.0
Subject: sub26
Predicted    : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Ground Truth : [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Evaluation until this subject: 
UF1: 0.641 | UAR: 0.6667
Subject: sub20
Predicted    : [0, 0]
Ground Truth : [0, 0]
Evaluation until this subject: 
UF1: 0.6444 | UAR: 0.6667
Subject: sub21
Predicted    : [1]
Ground Truth : [0]
Evaluation until this subject: 
UF1: 0.6344 | UAR: 0.6444
Subject: sub24
Predicted    : [2, 0, 0]
Ground Truth : [2, 0, 0]
Evaluation until this subject: 
UF1: 0.6381 | UAR: 0.6471
Subject: sub22
Predicted    : [0, 0]
Ground Truth : [0, 0]
Evaluation until this subject: 
UF1: 0.641 | UAR: 0.6491
Subject: sub16
Predicted    : [0, 1, 0]
Ground Truth : [1, 1, 0]
Evaluation until this subject: 
UF1: 0.746 | UAR: 0.7333
Subject: sub19
Predicted    : [2, 2, 2, 2, 2, 0, 0, 0, 1, 1, 1]
Ground Truth : [2, 2, 2, 2, 2, 0, 0, 0, 1, 1, 1]
Evaluation until this subject: 
UF1: 0.8611 | UAR: 0.8427
Subject: sub17
Predicted    : [2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1]
Ground Truth : [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1]
Evaluation until this subject: 
UF1: 0.9018 | UAR: 0.8903
Subject: sub23
Predicted    : [0, 0, 0, 0, 0, 1, 0, 0]
Ground Truth : [0, 0, 0, 0, 0, 0, 0, 1]
Evaluation until this subject: 
UF1: 0.8801 | UAR: 0.87
Subject: sub15
Predicted    : [0, 2, 0]
Ground Truth : [1, 2, 0]
Evaluation until this subject: 
UF1: 0.8695 | UAR: 0.8565
Subject: sub14
Predicted    : [0, 1, 1]
Ground Truth : [1, 1, 1]
Evaluation until this subject: 
UF1: 0.8722 | UAR: 0.8587
Subject: sub12
Predicted    : [0, 0, 1, 0, 0, 1, 1, 2, 2, 2, 2]
Ground Truth : [0, 0, 0, 0, 0, 1, 1, 2, 2, 2, 2]
Evaluation until this subject: 
UF1: 0.8757 | UAR: 0.8663
Subject: sub08
Predicted    : [1]
Ground Truth : [0]
Evaluation until this subject: 
UF1: 0.8672 | UAR: 0.8611
Subject: sub13
Predicted    : [0, 1]
Ground Truth : [1, 1]
Evaluation until this subject: 
UF1: 0.864 | UAR: 0.8563
Subject: sub09
Predicted    : [0, 0, 0, 0, 0, 1, 0, 1, 1, 1]
Ground Truth : [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]
Evaluation until this subject: 
UF1: 0.8754 | UAR: 0.8672
Subject: sub07
Predicted    : [1, 0, 0, 0, 0]
Ground Truth : [0, 0, 0, 0, 0]
Evaluation until this subject: 
UF1: 0.8707 | UAR: 0.8643
Subject: sub06
Predicted    : [2, 2, 0, 0]
Ground Truth : [2, 2, 1, 0]
Evaluation until this subject: 
UF1: 0.8647 | UAR: 0.8569
Subject: sub11
Predicted    : [0, 0, 0, 0]
Ground Truth : [0, 0, 0, 0]
Evaluation until this subject: 
UF1: 0.8666 | UAR: 0.8584
Subject: sub05
Predicted    : [2, 2, 0, 2, 2, 1]
Ground Truth : [2, 2, 2, 2, 2, 1]
Evaluation until this subject: 
UF1: 0.8601 | UAR: 0.8463
Subject: sub04
Predicted    : [0, 1]
Ground Truth : [0, 0]
Evaluation until this subject: 
UF1: 0.8545 | UAR: 0.8427
Subject: sub03
Predicted    : [0, 0, 0, 0, 2]
Ground Truth : [0, 0, 0, 0, 2]
Evaluation until this subject: 
UF1: 0.8567 | UAR: 0.8449
Subject: s20
Traceback (most recent call last):
  File "main.py", line 232, in <module>
    main(config)
  File "main.py", line 152, in main
    X_train = torch.Tensor(X_train).permute(0,3,1,2)
RuntimeError: number of dims don't match in permute

**Comment by genbing99** [comment]
Hi, it seems like the way the files indexed on your os FileSystem is different. The order of the printed output should be similar to the file 'STSTNet_python_logfile.txt'.
