### ISSUE TITLE
How do I recognize microexpressions use my own test examples?

### ISSUE THREAD

**Issue by YUZHIWANG-bug** [christy1206/STSTNet#6]
Dear author, it is my great honor to star your project. I would like to ask you how to use your project to recognize micro-expressions in videos or pictures

**Comment by genbing99** [comment]
Hi, you need to extract the optical flow features using the pre-determined onset and apex frames. Then use the pre-trained model to predict the emotion. Details are provided in the research paper and README file.

**Comment by YUZHIWANG-bug** [comment]
> Hi, you need to extract the optical flow features using the pre-determined onset and apex frames. Then use the pre-trained model to predict the emotion. Details are provided in the research paper and README file.

I'm sorry that the reply was not timely. I will try as you said. Thank you very much!
